=== folio-org/mod-ebsconet/src/main/resources/swagger.api/schemas/mod-orders/po_line.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "composite purchase order line with dereferenced/expanded orders fields",
  "type": "object",
  "properties": {
    "id": {
      "description": "UUID identifying this purchase order line",
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    },
    "cancellationRestriction": {
      "description": "whether or not there are cancellation restrictions for this purchase order line",
      "type": "boolean"
    },
    "cancellationRestrictionNote": {
      "description": "free-form notes related to cancellation restrictions",
      "type": "string"
    },
    "cost": {
      "description": "cost details associated with this purchase order line",
      "type": "object",
      "$ref": "cost.json"
    },
    "details": {
      "description": "details about this purchase order line",
      "type": "object",
      "$ref": "details.json"
    },
    "fundDistribution": {
      "description": "the UUIDs of the fund distribution records for this purchase order line",
      "id": "fundDistribution",
      "type": "array",
      "items": {
        "description": "a fund distribution record",
        "type": "object",
        "$ref": "fund_distribution.json"
      }
    },
    "poLineNumber": {
      "description": "A human readable number assigned to this PO line",
      "type": "string",
      "pattern": "^[a-zA-Z0-9]{1,22}-[0-9]{1,3}$",
      "readOnly": true
    },
    "publisher": {
      "description": "publisher of the material",
      "type": "string"
    },
    "purchaseOrderId": {
      "description": "UUID of this parent purchase order",
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    },
    "renewalNote": {
      "description": "Renewal note for this purchase order line",
      "type": "string"
    },
    "vendorDetail": {
      "description": "details related to the vendor of this purchase order line",
      "type": "object",
      "$ref": "vendor_detail.json"
    }
  },
  "additionalProperties": false,
  "required": [
    "cost"
  ]
}

=== folio-org/mod-ebsconet/src/test/resources/mockdata/order_line.json
{
  "cost": {
    "quantityPhysical": 1,
    "listUnitPrice": 1,
    "currency": "USD"
  },
  "purchaseOrderId": "d79b0bcc-DcAD-1E4E-Abb7-DbFcaD5BB3bb",
  "vendorDetail": {
    "vendorAccount": "1234-56",
    "referenceNumbers": [
      {
        "refNumber": "123456-78",
        "refNumberType": "Vendor title number"
      }
    ]
  },
  "publisher": "MIT Press",
  "poLineNumber": "268758-03",
  "id": "c0d08448-347b-418a-8c2f-5fb50248d67e",
  "cancellationRestriction": false,
  "cancellationRestrictionNote": "Cancellation Restriction Note",
  "fundDistribution": [
    {
      "code": "HIST",
      "distributionType": "percentage"
    }
  ]
}
